name: publish package

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  extract-and-tag:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install yq
        run: |
          sudo add-apt-repository ppa:rmescandon/yq
          sudo apt update
          sudo apt install yq -y

      - name: Extract version from YAML
        run: |
          VERSION=$(yq e '.info.version' ./openapi-spec/chatbots_api.yml)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: ${{ env.VERSION }}
          body: ${{ github.event.pull_request.body }}
          draft: false
